### ISSUE TITLE
Enable check-enterprise-isolation on travis

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/tools#15]
As we're very close to check-in some isolation tests specific to citus-enterprise (i.e., `check-enterprise-isolation`), I'm trying to find the correct way of running those tests on the enterprise repo.

Could anyone guide me?

What I have in mind is  
1.  Add `USE_CUSTOM_PG_FOR_ENTERPRISE` flag to `travis.yml` on `citus-enterprise`
2. Add `else if` that checks the above flag on `pg_travis_multi_test`. 

Does that sound reasonable?

**Comment by onderkalaci** [comment]
@jasonmp85 @byucesoy Any comments?

Thanks!

**Comment by byucesoy** [comment]
I think easiest way to achieve that is adding `check-enterprise-isolation` target to the `citus-enterprise/src/test/regress/Makefile` and adding it as dependency to the `check-isolation`.

**Comment by onderkalaci** [comment]
Thanks, @byucesoy, that did the trick!
