### ISSUE TITLE
Change github actions array notation into yaml list notation

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/tools#160]
When developing yml , list parameter notation is [ ... ] . However our standard notation is 
-a
-b
-c

Fix all the pipeline in accordance with this notation
Affected Repos and branches

Tools
- [x] develop
Packaging
- [x] all-citus
- [x] all-enterprise
- [x] all-pgautofailover
- [x] all-pgautofailover-enterprise
- [ ] all-pgxn

Docker
- [ ] master

**Comment by hanefi** [comment]
Consider adding all affected repos, branches, or pipeline names in a checklist.

It will be easier to track what part of this is complete, and what needs to be done

**Comment by gurkanindibay** [comment]
Added a checklit
