### ISSUE TITLE
Update os package installation scripts

### ISSUE THREAD

**Issue by hanefi** [citusdata/tools#224]
I realized that PackageCloud updated their [scripts to install package repositories](https://packagecloud.io/citusdata/community/install#bash). We should review their changes and update our scripts as well.

**Comment by gurkanindibay** [comment]
I checked our current installation scripts for both centos/7 and ubuntu/focal. All works well. I will check effects of change when I'm available

**Comment by hanefi** [comment]
Our scripts may work just fine. I just wanted to note that PackageCloud made some improvements that we can copy into our own scripts to benefit from that improvement.

**Comment by hanefi** [comment]
We ran into some issues with gpg keys, and we suspect that this is the root cause.

**Comment by hanefi** [comment]
Remaining scripts updated by https://github.com/citusdata/packaging/pull/932
