### ISSUE TITLE
Enable valgrind tests to get parameters

### ISSUE THREAD

**Issue by onderkalaci** [citusdata/tools#41]
Currently the users to to get the e-mail and the branch that is checked-out on the remote side is hard-coded. 

That requires certain workflow such as creating a branch, changing the code in the branch to use a specified branch, and finally undoing the code changes before merging the code.

It'd be good make those things parametric, externally provided to `launch-test-instance.sh` so that we don't need to follow the above hack.

**Comment by onurctirtir** [comment]
We don't use this repo's valgrind tooling anymore, so closing.
